colorScheme = "congo"
homepage.layout = "card"

# Theme Choices #
# ------------- #
# Blowfish (default) #
# Avocado #
# Fire #
# Forest #
# Princess #
# Neon #
# Bloody #
# Terminal #
# Marvel #
# Noir #
# Autumn #
# Congo #
# Slate #
